### DISCUSSION TITLE
[OP Stack Deployment] Help!! op-deployer apply ERROR

### DISCUSSION THREAD

**Discussion by Guan21** [ethereum-optimism/developers#734] [Deploying the OP Stack] [answered]
### Did you check the documentation?

- [x] Yes

### Did you check for duplicate questions?

- [X] Yes

### Issue Description

Hi, 
I am a new L2 developer trying to build my own Rollup testnet. I followed the tutorials in [OPTIMISM DOCS](https://docs.optimism.io/operators/chain-operators/tutorials/create-l2-rollup#step-1-deploy-the-l1-contracts) and successfully generated the getting-started/.deploy file. Next, I built the op-deployer and created a .deployer directory [using the specified command](https://docs.optimism.io/operators/chain-operators/tools/op-deployer#init-configure-your-chain). After modifying the intent.toml file, I encountered an error...

is any wrong in my intent.toml  file

```
`configType = "standard"
l1ChainID = 11155111
fundDevAccounts = false
useInterop = false
l1ContractsLocator = "tag://op-contracts/v1.8.0-rc.4"
l2ContractsLocator = "tag://op-contracts/v1.7.0-beta.1+l2-contracts"

[superchainRoles]
  proxyAdminOwner = "0x1eb2ffc903729a0f03966b917003800b145f56e2"
  protocolVersionsOwner = "0xfd1d2e729ae8eee2e146c033bf4400fe75284301"
  guardian = "0x7a50f00e8d05b95f98fe38d8bee366a7324dcf7e"

[[chains]]
  id = "0x000000000000000000000000000000000000000000000000000000000000a455"
  baseFeeVaultRecipient = "0x14a8bA883788935f318Ef64c24878CAcFa545191"  --> $GS_ADMIN_ADDRESS
  l1FeeVaultRecipient = "0x14a8bA883788935f318Ef64c24878CAcFa545191"  --> $GS_ADMIN_ADDRESS
  sequencerFeeVaultRecipient = "0x14a8bA883788935f318Ef64c24878CAcFa545191"  --> $GS_ADMIN_ADDRESS
  eip1559DenominatorCanyon = 250
  eip1559Denominator = 50
  eip1559Elasticity = 6
  [chains.roles]
    l1ProxyAdminOwner = "0x14a8bA883788935f318Ef64c24878CAcFa545191"  --> $GS_ADMIN_ADDRESS
    l2ProxyAdminOwner = "0x14a8bA883788935f318Ef64c24878CAcFa545191"  --> $GS_ADMIN_ADDRESS
    systemConfigOwner = "0x14a8bA883788935f318Ef64c24878CAcFa545191"  --> $GS_ADMIN_ADDRESS
    unsafeBlockSigner = "0x79492d32865EF14E1d60D68ADaa6495533c35Db8"  --> $GS_SEQUENCER_ADDRESS
    batcher = "0x0864902D028C348A88014DE98F01793c3A5D796d"  --> $GS_BATCHER_ADDRESS
    proposer = "0xc72c6998ade57500e54d77FE12381d8Da7a045C8"  --> $GS_PROPOSER_ADDRESS
    challenger = "0x14a8bA883788935f318Ef64c24878CAcFa545191"  --> $GS_ADMIN_ADDRESS
```

### Logs

`op-deployer % ./bin/op-deployer apply --workdir .deployer \
  --l1-rpc-url <changed my rpc-url>\
  --private-key <changed my GS_ADMIN_PRIVATE_KEY>
 100% |████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| (52/52 MB, 4.8 MB/s)         
 100% |████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| (57/57 MB, 3.9 MB/s)         
INFO [02-21|15:30:41.632] Initialized path database                readonly=true cache=0.00B buffer=0.00B history=0
INFO [02-21|15:30:41.636] initializing pipeline                    stage=init strategy=live
INFO [02-21|15:30:42.191] superchain deployment not needed         stage=deploy-superchain
INFO [02-21|15:30:42.192] implementations deployment not needed    stage=deploy-implementations
INFO [02-21|15:30:42.193] deploying OP chain using local allocs    stage=deploy-opchain id=0x000000000000000000000000000000000000000000000000000000000000a455
WARN [02-21|15:30:45.774] callframe                                depth=1 byte4=0xfc4dcacb addr=0x551618101B3999B61c266b9B3f8489195d32a328 callsite= label=DeployOPChain
WARN [02-21|15:30:45.776] Revert                                   addr=0x551618101B3999B61c266b9B3f8489195d32a328 label=DeployOPChain err="execution reverted" revertMsg="unrecognized 4 byte signature: 470f50dc" depth=1
WARN [02-21|15:30:45.776] Fault                                    addr=0x551618101B3999B61c266b9B3f8489195d32a328 label=DeployOPChain err="execution reverted" depth=1
WARN [02-21|15:30:45.776] callframe                                depth=1 byte4=0xfc4dcacb addr=0x551618101B3999B61c266b9B3f8489195d32a328 callsite= label=DeployOPChain
WARN [02-21|15:30:45.776] Revert                                   addr=0x551618101B3999B61c266b9B3f8489195d32a328 label=DeployOPChain err="execution reverted" revertMsg="unrecognized 4 byte signature: 470f50dc" depth=0
Application failed: error in pipeline stage apply: error deploying OP chain: failed to run DeployOPChain.s.sol script: revert: unrecognized 4 byte signature: 470f50dc`

**Comment by jsvisa** [comment]
I'm reproduing it with the latest develop branch, also meets this issue:

```
INFO [02-21|18:24:23.566] superchain deployment not needed         stage=deploy-superchain
INFO [02-21|18:24:23.569] implementations deployment not needed    stage=deploy-implementations
INFO [02-21|18:24:23.570] deploying OP chain using local allocs    stage=deploy-opchain id=0x0000000000000000000000000000000000000000000000000000000000000998
WARN [02-21|18:24:25.738] callframe                                depth=1 byte4=0xfc4dcacb addr=0x551618101B3999B61c266b9B3f8489195d32a328 callsite= label=DeployOPChain
WARN [02-21|18:24:25.739] Revert                                   addr=0x551618101B3999B61c266b9B3f8489195d32a328 label=DeployOPChain err="execution reverted" revertMsg="unrecognized 4 byte signature: 470f50dc" depth=1
WARN [02-21|18:24:25.739] Fault                                    addr=0x551618101B3999B61c266b9B3f8489195d32a328 label=DeployOPChain err="execution reverted" depth=1
WARN [02-21|18:24:25.739] callframe                                depth=1 byte4=0xfc4dcacb addr=0x551618101B3999B61c266b9B3f8489195d32a328 callsite= label=DeployOPChain
WARN [02-21|18:24:25.739] Revert                                   addr=0x551618101B3999B61c266b9B3f8489195d32a328 label=DeployOPChain err="execution reverted" revertMsg="unrecognized 4 byte signature: 470f50dc" depth=0
Application failed: error in pipeline stage apply: error deploying OP chain: failed to run DeployOPChain.s.sol script: revert: unrecognized 4 byte signature: 470f50dc
```

Will take a deep look later

**Reply by jsvisa** [reply, marked as answer]
Seems it's a op-deployer's bug, currently if you want to deploy with op-deployer, could you plase try [op-deployer/v0.0.10](https://github.com/ethereum-optimism/optimism/releases/tag/op-deployer%2Fv0.0.10) instead of the latest develop branch. And with the below contracts:

```toml
l1ContractsLocator = "tag://op-contracts/v1.6.0"
l2ContractsLocator = "tag://op-contracts/v1.7.0-beta.1+l2-contracts"
```


This is a test tx to deploy the chains https://sepolia.etherscan.io/tx/0x642926f6e1535f242e070b2e2b033895870e21bf81659a2b3e47a0c655d1bbb5

**Reply by Guan21** [reply]
@jsvisa 
Thank you for checking!
Awesome, it works!

Could you please send me the intent.toml file that you used in the test?

**Reply by jsvisa** [reply]
@Guan21 FYI, maybe you need to change the owner and chain ids for your own requirements


```toml
configType = "standard"
l1ChainID = 11155111
fundDevAccounts = false
useInterop = false
l1ContractsLocator = "tag://op-contracts/v1.6.0"
l2ContractsLocator = "tag://op-contracts/v1.7.0-beta.1+l2-contracts"

[superchainRoles]
  proxyAdminOwner = "0x1eb2ffc903729a0f03966b917003800b145f56e2"
  protocolVersionsOwner = "0x79add5713b383daa0a138d3c4780c7a1804a8090"
  guardian = "0x7a50f00e8d05b95f98fe38d8bee366a7324dcf7e"

[[chains]]
  id = "0x000000000000000000000000000000000000000000000000000000010000a469"
  baseFeeVaultRecipient = "0x5946aeFd6c21D9cE4caE534A6ee47d6708a92FB4"
  l1FeeVaultRecipient = "0x5946aeFd6c21D9cE4caE534A6ee47d6708a92FB4"
  sequencerFeeVaultRecipient = "0x5946aeFd6c21D9cE4caE534A6ee47d6708a92FB4"
  eip1559DenominatorCanyon = 250
  eip1559Denominator = 50
  eip1559Elasticity = 6
  [chains.roles]
    l1ProxyAdminOwner = "0x1Eb2fFc903729a0F03966B917003800b145F56E2"
    l2ProxyAdminOwner = "0xC40445CD88dDa2A410F86F6eF8E00fd52D8381FD"
    systemConfigOwner = "0xB32296E6929F2507dB8153A64b036D175Ac6E89e"
    unsafeBlockSigner = "0xA53526b516df4eEe3791734CE85311569e0eAD78"
    batcher = "0x8680d36811420359093fd321ED386a6e76BE2AF3"
    proposer = "0x41b3B204099771aDf857F826015703A1030b6675"
    challenger = "0xfd1D2e729aE8eEe2E146c033bf4400fE75284301"
```
