### DISCUSSION TITLE
[OP Stack Deployment] Deploy my own fork of the op-contracts/v1.8.0 using op-deployer v0.0.13

### DISCUSSION THREAD

**Discussion by seromenho** [ethereum-optimism/developers#763] [Deploying the OP Stack]
### Did you check the documentation?

- [X] Yes

### Did you check for duplicate questions?

- [X] Yes

### Issue Description

I'm trying to deploy a chain using a **forked version** of the `op-contracts/v1.8.0` release.  

Here's my current configuration:
```toml
configType = "standard"
l1ChainID = 11155111
fundDevAccounts = false
useInterop = false
l1ContractsLocator = "file://Users/s/optimism"
l2ContractsLocator = "file://Users/s/optimism"
```

I’m attempting to use the file:// schema instead of the tag:// schema, as described in the [OP Deployer Book](https://devdocs.optimism.io/op-deployer/reference-guide/artifacts-locators.html), but it doesn’t seem to be working.

Any insights or tips would be greatly appreciated!

Thank you in advance.

### Logs

```console
$ op-deployer apply --workdir .deployer --l1-rpc-url  $L1_RPC_URL --private-key $OP_DEPLOYER_PK
Application failed: failed to validate intent-config-type=standard: tag '' not found in standard versions
```

### Additional Information
op-contracts: fork of `op-contracts/v1.8.0`
op-deployer: `op-deployer/v0.0.13´

_No response_
