### DISCUSSION TITLE
[OP Stack Deployment] Deploy chain with Alt-DA + L2OutputOracle (fault proofs disabled)  op-contracts/v1.8.0 op-deployer/v0.0.13

### DISCUSSION THREAD

**Discussion by seromenho** [ethereum-optimism/developers#767] [Deploying the OP Stack]
### Did you check the documentation?

- [X] Yes

### Did you check for duplicate questions?

- [X] Yes

### Issue Description

I'm trying to deploy an OP Stack chain with a specific configuration: Alt-DA enabled, fault proofs disabled, and using L2OutputOracle. However, I'm encountering issues where the deployment process seems always to deploy the fault proof contracts despite my configuration.
Here's the relevant part of my intent.toml file:
```toml
configType = "standard-overrides"
l1ChainID = 11155111
fundDevAccounts = true
useInterop = false
l1ContractsLocator = "tag://op-contracts/v1.8.0-rc.4" # L1 smart contracts versions
l2ContractsLocator = "tag://op-contracts/v1.7.0-beta.1+l2-contracts" # L2 smart contracts versions

[[chains]]
  id = "0x000000000000000000000000000000000000000000000000000000000000a455"
  baseFeeVaultRecipient = "0x..."
  l1FeeVaultRecipient = "0x..."
  sequencerFeeVaultRecipient = "0x..."
  eip1559DenominatorCanyon = 250
  eip1559Denominator = 50
  eip1559Elasticity = 6
  [chains.roles]
    l1ProxyAdminOwner = "0x..."
    l2ProxyAdminOwner = "0x..."
    systemConfigOwner = "0x..."
    unsafeBlockSigner = "0x..."
    batcher = "0x..."
    proposer = "0x..."
    challenger = "0x..."
  [chains.dangerousAltDAConfig]
    useAltDA = true
    daCommitmentType = "KeccakCommitment"
    daChallengeWindow = 16
    daResolveWindow = 16
    daBondSize = 1000000
    daResolverRefundPercentage = 0

[globalDeployOverrides]
  useFaultProofs = false
  l2OutputOracleSubmissionInterval = 1800
  l2OutputOracleProposer = "0x..."
  l2OutputOracleChallenger = "0x..."
```

After running the deployment, I can see that both the fault proof contracts (DisputeGameFactory, FaultDisputeGame, etc.) are deployed, but the L2OutputOracle is not deployed, despite setting useFaultProofs = false

#### Questions:
1. Is it possible to use op-deployer to create a chain with Alt-DA + L2OutputOracle (fault proofs disabled)? Does version `op-deployer/v0.0.13` of op-deployer support this configuration? How?
2. What is the expected behaviour when setting useFaultProofs = false? Should this deploy L2OutputOracle, or is additional configuration required?

Thank you

### Feedback

It would be helpful to have:
1. Clear documentation on the compatibility between Alt-DA mode and L2OutputOracle for the latest (non-RC) version of the contracts.
2. Examples of working intent.toml configurations for different chain setups (standard, Alt-DA with fault proofs, Alt-DA without fault proofs, etc.)
non-RC
